#!/bin/bash
echo "Hello user, welcome to the script."
firstline=$(head -n 1 source/changelog.md)
read -a splitfirstline <<< $firstline
echo ${splitfirstline[1]}
version=${splitfirstline[1]}
echo "You are building version" $version
echo 'Do you want to continue? (enter "1" for yes, "0" for no)'
read versioncontinue
if [ $versioncontinue -eq 1 ]
then
	for filename in source/*
  do
  	echo $filename
		if [ $filename == "source/secretinfo.md" ]
    then
    	echo "Not Copying " $filename
    else
    	echo "copying " $filename
      cp $filename build/.
    fi
  done
else
	echo "Please come back when you are ready."
fi

cd build/
echo "Build version $version contains: "
ls
cd ..
